version: 2
jobs:
  build:
    working_directory: ~/feedbackfruits-knowledge-mit-miner
    docker:
      - image: node:8
        environment:
          NODE_ENV: test
          OUTPUT_TOPIC: test_update_requests
          KAFKA_ADDRESS: localhost:9092
          START_PAGE: 1
          END_PAGE: 2
          PAGE_SIZE: 10
      - image: wurstmeister/zookeeper:latest
      - image: wurstmeister/kafka:1.0.0
        environment:
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_CREATE_TOPICS: "test_updates:1:1,test_update_requests:1:1"
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: yarn run coverage

      - store_artifacts:
          path: coverage

      - run:
          name: Install Heroku CLI
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - deploy:
          name: Deploy to Heroku
          command: |
            cat >~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_TOKEN
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_TOKEN
            EOF
            chmod 600 ~/.netrc # Heroku cli complains about permissions without this

            mkdir -p ~/.ssh
            ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
            if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
              heroku config:add GIT_TAG=`git describe --tags --always` --app fbf-knowledge-mit-miner
              git push git@heroku.com:fbf-knowledge-mit-miner.git $CIRCLE_SHA1:refs/heads/master -f
              heroku ps:scale web=0 -a fbf-knowledge-mit-miner
              heroku run:detached yarn start -a fbf-knowledge-mit-miner
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              heroku config:add GIT_TAG=`git describe --tags --always` --app staging-fbf-knowledge-mit-mine
              git push git@heroku.com:staging-fbf-knowledge-mit-mine.git $CIRCLE_SHA1:refs/heads/master -f
              heroku ps:scale web=0 -a staging-fbf-knowledge-mit-mine
              heroku run:detached yarn start -a staging-fbf-knowledge-mit-mine
            fi
