declare const NAME: string, KAFKA_ADDRESS: string, OUTPUT_TOPIC: string, S3_ACCESS_KEY_ID: string, S3_SECRET_ACCESS_KEY: string, S3_BUCKET: string;
declare const CONCURRENCY: number;
export { NAME, KAFKA_ADDRESS, OUTPUT_TOPIC, CONCURRENCY, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_BUCKET, };
