"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').config();
const { NAME = 'feedbackfruits-knowledge-mit-miner', KAFKA_ADDRESS = 'tcp://localhost:9092', OUTPUT_TOPIC = 'staging_mit_update_requests', S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_BUCKET = 'open-learning-course-data-rc', } = process.env;
exports.NAME = NAME;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.OUTPUT_TOPIC = OUTPUT_TOPIC;
exports.S3_ACCESS_KEY_ID = S3_ACCESS_KEY_ID;
exports.S3_SECRET_ACCESS_KEY = S3_SECRET_ACCESS_KEY;
exports.S3_BUCKET = S3_BUCKET;
const CONCURRENCY = parseInt(process.env.CONCURRENCY) || 1;
exports.CONCURRENCY = CONCURRENCY;
